### ISSUE TITLE
ImportError: cannot import name 'Feature' from 'setuptools'

### ISSUE THREAD

**Issue by sjorsvanheuveln** [NakamotoInstitute/nakamotoinstitute.org#236]
I'm getting this error whilst installing the requirements.

```
ERROR: Command errored out with exit status 1:
     command: /Users/sjorsvanheuveln/Desktop/Bitcoin/programming/nakamotoinstitute.org/venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/8f/mg9l1rg90j513t29j3v7zkv40000gn/T/pip-install-oa0andvm/pyscss_e104aacf2a35476b8103b9ebe6c62eae/setup.py'"'"'; __file__='"'"'/private/var/folders/8f/mg9l1rg90j513t29j3v7zkv40000gn/T/pip-install-oa0andvm/pyscss_e104aacf2a35476b8103b9ebe6c62eae/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/8f/mg9l1rg90j513t29j3v7zkv40000gn/T/pip-pip-egg-info-feevp4fm
         cwd: /private/var/folders/8f/mg9l1rg90j513t29j3v7zkv40000gn/T/pip-install-oa0andvm/pyscss_e104aacf2a35476b8103b9ebe6c62eae/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/8f/mg9l1rg90j513t29j3v7zkv40000gn/T/pip-install-oa0andvm/pyscss_e104aacf2a35476b8103b9ebe6c62eae/setup.py", line 9, in <module>
        from setuptools import setup, Extension, Feature
    ImportError: cannot import name 'Feature' from 'setuptools' (/Users/xxxxxx/Desktop/Bitcoin/programming/nakamotoinstitute.org/venv/lib/python3.9/site-packages/setuptools/__init__.py)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by bitstein** [comment]
I am working on a major refactor that updates almost everything, so hopefully this will be fixed for you after that.

**Comment by sjorsvanheuveln** [comment]
Awesome. Can't wait.
